### ISSUE TITLE
Bluetooth module outputs device's Bluetooth MAC Address

### ISSUE THREAD

**Issue by dcoobs** [munkireport/bluetooth#10]
I've noticed that the Bluetooth module is outputting the device's Bluetooth MAC
<img width="842" alt="MRBluetoothMAC" src="https://user-images.githubusercontent.com/12276948/146794745-4150af91-a961-4f84-8311-2161e9ad96b7.png">

**Comment by tuxudo** [comment]
Fixed in version 3.1 of the module
