### ISSUE TITLE
Not showing devices in Monterey

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/bluetooth#12]
If I run `system_profiler SPBluetoothDataType` I get a list of all my bluetooth devices, but the MR script only lists the built-in interface.

MR only shows this:

<img width="477" alt="Screenshot 2022-06-11 at 18 55 05" src="https://user-images.githubusercontent.com/16665880/173199624-59ca79d4-4fda-4aa5-a882-48013d5c28c6.png">

I also noticed that on my Intel iMac (12.4.0) `system_profiler SPBluetoothDataType` displays more info about the interface than is shown in MR. In my case I see:

```Bluetooth Controller:
          Address: A4:82:.....
          State: On
          Chipset: BCM_4364B3
          Discoverable: Off
          Firmware Version: v82 c4200
          Product ID: 0x0001
          Supported services: 0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
          Transport: UART
          Vendor ID: 0x004C (Apple)```

This is followed with the full device list

**Comment by tuxudo** [comment]
This is fixed in version v4.0 of the module.
